name: 'Terraform Deploy'
description: 'Deploys the Terraform'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
  serviceprinciple_key:
    description: 'Deployment environment'
    required: true
  subscription_id:
    description: 'ID for deployment subscription'
    required: true
    


runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      id: TF-Setup
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Validate
      id: validate
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: |
        terraform init -backend-config="./backend/${{ inputs.environment }}-backend.hcl"
        terraform validate
      env:
        TF_VAR_serviceprinciple_key: ${{ inputs.serviceprinciple_key }}
        TF_VAR_environment: ${{ inputs.environment }}
        TF_VAR_subscription_id: ${{ inputs.subscription_id }}
      working-directory: ./terraform

    #- name: Terraform Format
    #  id: Format
    #  if: github.ref == 'refs/heads/main'
    #  shell: bash
    #  run: |
    #    terraform init -backend-config="./backend/${{ inputs.environment }}-backend.hcl"
    #    terraform fmt -check
    #  env:
    #    TF_VAR_serviceprinciple_key: ${{ inputs.serviceprinciple_key }}
    #    TF_VAR_environment: ${{ inputs.environment }}
    #    TF_VAR_subscription_id: ${{ inputs.subscription_id }}
    #  working-directory: ./terraform


    - name: Terraform Plan
      id: plan
      shell: bash
      run: |
        terraform init -backend-config="./backend/${{ inputs.environment }}-backend.hcl"
        terraform plan -var-file="./config/common.tfvars" -var-file="./config/${{ inputs.environment }}.tfvars"
      env:
        TF_VAR_environment: ${{ inputs.environment }}
        TF_VAR_subscription_id: ${{ inputs.subscription_id }}
      working-directory: ./terraform

    - name: Terraform Apply
      id: apply
      shell: bash
      #if: ${{ github.event.inputs.runApply == 'true' }}
      run: |
        terraform init -backend-config="./backend/${{ inputs.environment }}-backend.hcl"
        terraform apply -var-file="./config/common.tfvars" -var-file="./config/${{ inputs.environment }}.tfvars" -auto-approve -input=false
      env:
        TF_VAR_environment: ${{ inputs.environment }}
        TF_VAR_subscription_id: ${{ inputs.subscription_id }}
      working-directory: ./terraform
