name: Terraform Destroy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 1-5'

jobs:

  dev_deploy:
    runs-on: ubuntu-latest
    name: "Dev Terraform Deploy"
    #environment: development 
    env: 
      ARM_CLIENT_ID: ${{ secrets.TERRAFORM_CLIENT_ID }}
      name: Dev Deploy
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Dev Terraform
        id: dev-tf-deploy
        uses: ./.github/actions/terraform-destroy
        env:
          ARM_TENANT_ID: ${{ secrets.TERRAFORM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.TERRAFORM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}
          ARM_ACCESS_KEY: ${{ secrets.TERRAFORM_ACCESS_KEY }}
          WORKING_DIRECTORY: ./terraform
        with:
          environment: dev
          serviceprinciple_key: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
          subscription_id: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}


  QA_deploy:
    name: "QA Terraform Deploy"
    runs-on: ubuntu-latest
    needs: dev_deploy
    #environment: development 
    env: 
      ARM_CLIENT_ID: ${{ secrets.TERRAFORM_CLIENT_ID }}
      name: Dev Deploy
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: QA Terraform
        id: qa-tf-deploy
        uses: ./.github/actions/terraform-destroy
        env:
          ARM_TENANT_ID: ${{ secrets.TERRAFORM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.TERRAFORM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}
          ARM_ACCESS_KEY: ${{ secrets.TERRAFORM_ACCESS_KEY2 }}
          WORKING_DIRECTORY: ./terraform
        with:
          environment: qa
          serviceprinciple_key: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
          subscription_id: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}          
  
